[package]
authors = ["Özer <ozer.cevikaslan@gmail.com>"]
name = "norwegian_id_validator"
description = "Norwegian ID number validation"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["norwegian-id", "id-validator", "norsk-nasjonalt-id"]
readme = "README.md"